package nic.goi.aarogyasetu.utility

/**
 * @author Niharika.Arora
 */
object Constants {
    val ALREADY_CONTRIBUTING = "You are already contributing"
    val PACKAGE = "package"
    val UNIQUE_ID = "did"
    val QR_PUBLIC_KEY = "qr_public_key"
    val PUSH_COVID_POSTIVE_P = "p"
    val DATA = "data"
    val AUTH = "Authorization"
    val PLATFORM = "pt"
    val OS = "os"
    val VERSION = "ver"
    val APP_VERSION_NAME = "ver-name"
    val LATITUDE = "lat"
    val LONGITUDE = "lon"
    val CONTENT_TYPE = "Content-Type"
    val CONTENT_TYPE_MULTIPART = "multipart/form-data; boundary=--------------------------855063967778865347844375"
    val ACCEPT_ENCODING = "Accept-Encoding"
    val GZIP = "gzip, deflate, br"
    val APPLICATION_JSON = "application/json"
    val BLUETOOTH_ADDRESS = "bluetooth_address"
    val MIN_VERSION = "min_version"
    val SPECIFIC_VERSION = "specific_version"
    val NOTIFICATION_CHANNEL = "cor_notification_channel"
    val NOTIFICATION_DESC = "Stay safe from COVID-19"
    val FROM_MY_WORKER = "fromMyWorker"
    val CONTENT_ENCODING = "Content-Encoding"
    val GZIP_VAL = "gzip"
    val FINISH = "finishbutton"
    val DOUBLE_SLASH = "://"
    val URL = "URL"
    val TITLE = "TITLE"
    val LOCALE = "locale"
    val LANG = "lang"
    val FIREBASE_DEFAULT_MSG_TEXT: CharSequence = "Important information for you. Please check."
    val WEB_NOT_SUPPORTED = "WebView issue on your device"
    val PLEASE_ALLOW_BLUETOOTH = "Bluetooth must be ON at all times to give you accurate safety updates."
    val PLEASE_ALLOW_LOCATION = "Location must be ON at all times to give you accurate safety updates."
    val NOT_TITLE = "title"
    val NOT_BODY = "body"
    val DOWNLOAD_FAIL = "Error while downloading.Please update from Play Store."
    val COVID_POSTIVE_PUSH_P_VALUE = "1"
    val PAGE_TITLE = "pageTitle"
    val EMPTY = ""
    val CLOSE = "Close"
    val TARGET = "target"
    val PUSH = "push_consent"
    val UTF = "UTF-8"
    val ROOT_ALERT = "You can't use this application due to security restrictions(rooted device)"
    val UPDATE = "Update"
    val FORCE_UPGRADE = "f_upgrade_android"
    val ALERT = "Alert"
    val IOS_URL_TEXT = "iOS : "
    val IOS_URL_LINK = "https://apps.apple.com/in/app/aarogyasetu/id1505825357"
    val SHARE_TEXT =
        "I recommend Aarogya Setu app to fight against COVID19. Please download and share it using this link Android : \n"
    val DEVICE_TYPE = "device-type"
    val HYPHEN = "-"
    val X_API_KEY = "x-api-key"
    val RESTART_TO_UPDATE = "Please restart to update"
    val UPLOAD_TYPE = "upload_type"
    val LEGACY_ISSUE = "Legacy advertising data too big"

    // Move to Localized string
    val ACTION_GOTO_SETTINGS = "Open settings"
    val ACTION_REMIND_LATER = "Remind later"
    val SPACE = " "
    val HEALTHY = "healthy"
    val MODERATE = "moderate"
    val HIGH = "high"
    val EXPIRY = "exp"
    val NAME = "name"
    val MOBILE = "mobile_no"
    val STATUS = "status"
    val BAR_CODE_PATH = "barcodeimage"
    val FILE_EXT = ".jpg"
    val QR_SCREEN_TAG = "QR_SCREEN_TAG "
    val MAX_INTRO_VIEWS = 2

    object Errors {
        val SELECT_OTHER_APP = "Select any other app to open this url"
    }

    object UPLOAD_TYPES {
        val PUSH_CONSENT = "push_consent"
        val BEING_TESTED = "being_tested"
        val TESTED_POSITIVE_CONSENT = "tested_positive_consent"
        val SELF_CONSENT = "self_consent"
    }
}
